#!/bin/bash

alias cls="echo -ne '\033c'"
alias sl='sl -e'
alias ls='ls --file-type --color=tty --group-directories-first'
#alias dir='dir --color=auto'
#alias vdir='vdir --color=auto'

# git
alias gs='git status -sb'
alias ga='git add'
alias gc='git commit -m'
alias gl='git log'

# mac-only
alias qlf='qlmanage -p "$1" >& /dev/null'

# utilities
alias myip='dig +short myip.opendns.com @resolver1.opendns.com'

#alias nano='$HOME/.dotfiles/bin/fileWritable.sh nano'
