#!/bin/bash

source ~/.dotfiles/colours

GIT_DIRTY=" ✗"
GIT_CLEAN=" ✓"

# Git branch prompt

function __git_prompt {
	GIT_PS1_SHOWDIRTYSTATE=1

	if [[ -n $(git status -s 2> /dev/null |grep -v ^# |grep -v "working directory clean") ]]; then
		state=$GIT_DIRTY
	else
		state=$GIT_CLEAN
	fi

	__git_ps1 " (%s$state )" | sed "s/ \([+*]\{1,\}\)$/\1/"
}

bash_prompt() {
	PS1="$extcyn\u$extblk@$extyel\h$extwht:$extred\W\[\$(randC)\]\$(__git_prompt)$extblk → $txtrst"
}

bash_prompt
unset bash_prompt
